/*
* generated by Xtext
*/
package de.wwu.md2.framework.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MD2OutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
