/*
 * generated by Xtext
 */
package de.wwu.md2.framework;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MD2UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return de.wwu.md2.framework.ui.internal.MD2Activator.getInstance().getInjector("de.wwu.md2.framework.MD2");
	}

}
