//
//  InitializeApplicationAction.h
//
//  Generated by MD2 framework on Fri May 17 11:44:44 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

#import "Action.h"
#import "AppDelegate.h"
#import "InitializeApplicationEvent.h"

@interface InitializeApplicationAction : Action
@end