//
//  Stylesheet.h
//
//  Generated by MD2 framework on Fri May 17 11:44:44 CEST 2013.
//  Copyright (c) 2012 Uni-Muenster. All rights reserved.
//

@interface Stylesheet : NSObject
{
	NSString *identifier;
	
	@private
	UIFont *font;
	UIColor *textColor;
	UIColor *backgroundColor;
	UIColor *tintColor;
}

@property (retain, nonatomic) NSString *identifier;
@property (retain, nonatomic) UIFont *font;
@property (retain, nonatomic) UIColor *textColor;

+(id) style;
-(void) applyToObject: (id) object idenfier: (NSString *) _identifier;
-(void) applyToObject: (id) object;

@end