<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mD2" nsURI="http://www.wwu.de/md2/framework/MD2" nsPrefix="mD2">
  <eClassifiers xsi:type="ecore:EClass" name="MD2Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="#//PackageDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelLayer" eType="#//MD2ModelLayer"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MD2ModelLayer"/>
  <eClassifiers xsi:type="ecore:EClass" name="PackageDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pkgName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View" eSuperTypes="#//MD2ModelLayer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewElements" upperBound="-1"
        eType="#//ViewElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewElementType" eSuperTypes="#//ViewElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ViewGUIElement" eSuperTypes="#//ViewElementType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContentElement" eSuperTypes="#//ViewGUIElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputElement" eSuperTypes="#//ContentElement #//MappableContentElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tooltipText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappableContentElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextInput" eSuperTypes="#//InputElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TextInputType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TextInputType">
    <eLiterals name="DEFAULT" literal="default"/>
    <eLiterals name="INPUT" value="1" literal="input"/>
    <eLiterals name="TEXTAREA" value="2" literal="textarea"/>
    <eLiterals name="PASSWORD" value="3" literal="password"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanInput" eSuperTypes="#//InputElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//BooleanInputType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BooleanInputType">
    <eLiterals name="DEFAULT" literal="default"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerInput" eSuperTypes="#//InputElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//IntegerInputType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IntegerInputType">
    <eLiterals name="DEFAULT" literal="default"/>
    <eLiterals name="INPUT" value="1" literal="input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberInput" eSuperTypes="#//InputElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//NumberInputType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placesSet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="places" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NumberInputType">
    <eLiterals name="DEFAULT" literal="default"/>
    <eLiterals name="INPUT" value="1" literal="input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateInput" eSuperTypes="#//InputElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DateInputType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DateInputType">
    <eLiterals name="DEFAULT" literal="default"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeInput" eSuperTypes="#//InputElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TimeInputType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeInputType">
    <eLiterals name="DEFAULT" literal="default"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateTimeInput" eSuperTypes="#//InputElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DateTimeInputType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DateTimeInputType">
    <eLiterals name="DEFAULT" literal="default"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionInput" eSuperTypes="#//InputElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//OptionInputType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumReference" eType="#//Enum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumBody" eType="#//EnumBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OptionInputType">
    <eLiterals name="DEFAULT" literal="default"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileUpload" eSuperTypes="#//InputElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" eType="#//StyleAssignment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buttonValueText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntitySelector" eSuperTypes="#//InputElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="textProposition" eType="#//ContentProviderPath"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutoGeneratedContentElement" eSuperTypes="#//ContentElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProvider" upperBound="-1"
        eType="#//ContentProviderReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filteredAttributes" upperBound="-1"
        eType="#//EntityPath" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//ContentElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" eType="#//StyleAssignment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDisabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tooltip" eSuperTypes="#//ContentElement #//MappableContentElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//ContentElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="src" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imgHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imgWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UploadedImageOutput" eSuperTypes="#//ContentElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imgHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imgWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="#//ContentElement #//MappableContentElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" eType="#//StyleAssignment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Spacer" eSuperTypes="#//ContentElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerElement" eSuperTypes="#//ViewGUIElement #//ContainerElementType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContentContainer" eSuperTypes="#//ContainerElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ViewElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubViewContainer" eSuperTypes="#//ContainerElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ContainerElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GridLayoutPane" eSuperTypes="#//ContentContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//GridLayoutPaneParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GridLayoutPaneParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlowLayoutPane" eSuperTypes="#//ContentContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//FlowLayoutPaneParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowLayoutPaneParam"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FlowDirection">
    <eLiterals name="HORIZONTAL" literal="horizontal"/>
    <eLiterals name="VERTICAL" value="1" literal="vertical"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlternativesPane" eSuperTypes="#//SubViewContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//CommonContainerParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TabbedAlternativesPane" eSuperTypes="#//SubViewContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="CommonContainerParam" eSuperTypes="#//GridLayoutPaneParam #//FlowLayoutPaneParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="TabSpecificParam" eSuperTypes="#//CommonContainerParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="ViewGUIElementReference" eSuperTypes="#//ViewElementType #//ContainerElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ViewGUIElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerElementType"/>
  <eClassifiers xsi:type="ecore:EClass" name="StyleAssignment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Style" eSuperTypes="#//ViewElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//StyleBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StyleBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//Color"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="italic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Color"/>
  <eClassifiers xsi:type="ecore:EEnum" name="NamedColor">
    <eLiterals name="AQUA" literal="aqua"/>
    <eLiterals name="BLACK" value="1" literal="black"/>
    <eLiterals name="BLUE" value="2" literal="blue"/>
    <eLiterals name="FUCHSIA" value="3" literal="fuchsia"/>
    <eLiterals name="GRAY" value="4" literal="gray"/>
    <eLiterals name="GREEN" value="5" literal="green"/>
    <eLiterals name="LIME" value="6" literal="lime"/>
    <eLiterals name="MAROON" value="7" literal="maroon"/>
    <eLiterals name="NAVY" value="8" literal="navy"/>
    <eLiterals name="OLIVE" value="9" literal="olive"/>
    <eLiterals name="PURPLE" value="10" literal="purple"/>
    <eLiterals name="RED" value="11" literal="red"/>
    <eLiterals name="SILVER" value="12" literal="silver"/>
    <eLiterals name="TEAL" value="13" literal="teal"/>
    <eLiterals name="WHITE" value="14" literal="white"/>
    <eLiterals name="YELLOW" value="15" literal="yellow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller" eSuperTypes="#//MD2ModelLayer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllerElements" upperBound="-1"
        eType="#//ControllerElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControllerElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowElement" eSuperTypes="#//ControllerElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultProcessChain" eType="#//ProcessChain"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initActions" unique="false"
        upperBound="-1" eType="#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processChain" upperBound="-1"
        eType="#//ProcessChain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoke" upperBound="-1"
        eType="#//InvokeDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomAction" eSuperTypes="#//Action #//ContainsCodeFragments"/>
  <eClassifiers xsi:type="ecore:EClass" name="CombinedAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" unique="false"
        upperBound="-1" eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterSignature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomCodeFragment"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfCodeBlock" eSuperTypes="#//ContainsCodeFragments">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//ConditionalExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElseCodeBlock" eSuperTypes="#//ContainsCodeFragments"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContainsCodeFragments">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeFragments" upperBound="-1"
        eType="#//CustomCodeFragment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractViewGUIElementRef" eSuperTypes="#//CustomCodeFragment #//ConditionalExpression #//SimpleExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//ViewElementType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tail" eType="#//AbstractViewGUIElementRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" eType="#//EntityPath"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simpleType" eType="#//SimpleDataTypeWrapper"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionDef"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventDef"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ElementEventType">
    <eLiterals name="ON_CLICK" literal="onClick"/>
    <eLiterals name="ON_CHANGE" value="1" literal="onChange"/>
    <eLiterals name="ON_LEFT_SWIPE" value="2" literal="onLeftSwipe"/>
    <eLiterals name="ON_RIGHT_SWIPE" value="3" literal="onRightSwipe"/>
    <eLiterals name="ON_WRONG_VALIDATION" value="4" literal="onWrongValidation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContentProviderEventType">
    <eLiterals name="ON_CHANGE" literal="onChange"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GlobalEventType">
    <eLiterals name="ON_CONNECTION_LOST" literal="onConnectionLost"/>
    <eLiterals name="ON_CONNECTION_REGAINED" value="1" literal="onConnectionRegained"/>
    <eLiterals name="ON_LOCATION_UPDATE" value="2" literal="onLocationUpdate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Validator" eSuperTypes="#//ControllerElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//ValidatorParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandardValidator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//ValidatorParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoteValidator" eSuperTypes="#//Validator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" eType="#//RemoteConnection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProvider" eType="#//ContentProviderReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provideAttributes" upperBound="-1"
        eType="#//ContentProviderPath" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorMessageParam" eSuperTypes="#//ValidatorParam #//RegExValidatorParam #//NumberRangeValidatorParam #//StringRangeValidatorParam #//DateRangeValidatorParam #//TimeRangeValidatorParam #//DateTimeRangeValidatorParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="#//SimpleExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegExValidatorParam" eSuperTypes="#//ValidatorParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumberRangeValidatorParam" eSuperTypes="#//ValidatorParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringRangeValidatorParam" eSuperTypes="#//ValidatorParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateRangeValidatorParam" eSuperTypes="#//ValidatorParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeRangeValidatorParam" eSuperTypes="#//ValidatorParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateTimeRangeValidatorParam" eSuperTypes="#//ValidatorParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="Main" eSuperTypes="#//ControllerElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workflowManager" eType="#//RemoteConnection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultConnection" eType="#//RemoteConnection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileUploadConnection" eType="#//RemoteConnection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentProvider" eSuperTypes="#//ControllerElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//DataType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="local" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" eType="#//RemoteConnection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterType" eType="#//FilterType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whereClause" eType="#//WhereClauseCondition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readonly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoteConnection" eSuperTypes="#//ControllerElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storagePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleDataTypeWrapper">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SimpleDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SimpleDataType">
    <eLiterals name="INTEGER" literal="integer"/>
    <eLiterals name="FLOAT" value="1" literal="float"/>
    <eLiterals name="STRING" value="2" literal="string"/>
    <eLiterals name="BOOLEAN" value="3" literal="boolean"/>
    <eLiterals name="DATE" value="4" literal="date"/>
    <eLiterals name="TIME" value="5" literal="time"/>
    <eLiterals name="DATE_TIME" value="6" literal="datetime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AllowedOperation">
    <eLiterals name="CREATE_OR_UPDATE" literal="save"/>
    <eLiterals name="READ" value="1" literal="load"/>
    <eLiterals name="DELETE" value="2" literal="remove"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FilterType">
    <eLiterals name="ALL" literal="all"/>
    <eLiterals name="FIRST" value="1" literal="first"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhereClauseCondition"/>
  <eClassifiers xsi:type="ecore:EClass" name="WhereClauseConditionalExpression" eSuperTypes="#//WhereClauseCondition"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractProviderReference" eSuperTypes="#//EventDef #//SimpleExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContentProviderReference" eSuperTypes="#//CustomCodeFragment #//AbstractProviderReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProvider" eType="#//ContentProvider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocationProviderReference" eSuperTypes="#//AbstractProviderReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="PathDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tail" eType="#//PathTail"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityPath" eSuperTypes="#//PathDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityRef" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractContentProviderPath" eSuperTypes="#//EventDef #//SimpleExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContentProviderPath" eSuperTypes="#//CustomCodeFragment #//PathDefinition #//AbstractContentProviderPath">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProviderRef" eType="#//ContentProvider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathTail">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeRef" eType="#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tail" eType="#//PathTail"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocationProviderPath" eSuperTypes="#//AbstractContentProviderPath">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationField" eType="#//LocationField"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LocationField">
    <eLiterals name="LATITUDE" literal="latitude"/>
    <eLiterals name="LONGITUDE" value="1" literal="longitude"/>
    <eLiterals name="ALTITUDE" value="2" literal="altitude"/>
    <eLiterals name="CITY" value="3" literal="city"/>
    <eLiterals name="STREET" value="4" literal="street"/>
    <eLiterals name="NUMBER" value="5" literal="number"/>
    <eLiterals name="POSTAL_CODE" value="6" literal="postalCode"/>
    <eLiterals name="COUNTRY" value="7" literal="country"/>
    <eLiterals name="PROVINCE" value="8" literal="province"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessChain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processChainSteps" upperBound="-1"
        eType="#//ProcessChainStep" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessChainStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" eType="#//AbstractViewGUIElementRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gotos" upperBound="-1"
        eType="#//ProcessChainGoToDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="#//SimpleExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessChainGoToDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="goto" eType="#//ProcessChainGoTo"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spec" eType="#//ProcessChainGoToSpec"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessChainGoTo"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessChainGoToSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//EventDef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="#//RESTMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//InvokeParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//ContentProviderPath"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="OnConditionEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//ConditionalExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalExpression"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ViewElementState">
    <eLiterals name="VALID" literal="valid"/>
    <eLiterals name="EMPTY" value="1" literal="empty"/>
    <eLiterals name="SET" value="2" literal="set"/>
    <eLiterals name="DEFAULT_VALUE" value="3" literal="defaultValue"/>
    <eLiterals name="DISABLED" value="4" literal="disabled"/>
    <eLiterals name="ENABLED" value="5" literal="enabled"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleExpression" eSuperTypes="#//ConditionalExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="WebServiceCall" eSuperTypes="#//ControllerElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="#//RESTMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queryparams" upperBound="-1"
        eType="#//RESTParam" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyparams" upperBound="-1"
        eType="#//RESTParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RESTParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//RESTValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RESTValue"/>
  <eClassifiers xsi:type="ecore:EEnum" name="RESTMethod">
    <eLiterals name="POST" literal="POST"/>
    <eLiterals name="GET" value="1" literal="GET"/>
    <eLiterals name="PUT" value="2" literal="PUT"/>
    <eLiterals name="DELETE" value="3" literal="DELETE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//MD2ModelLayer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElements" upperBound="-1"
        eType="#//ModelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enum" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumBody" eType="#//EnumBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumBody">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elements" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//AttributeType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extendedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeTypeParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReferencedTypeParam" eSuperTypes="#//AttributeTypeParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerTypeParam" eSuperTypes="#//AttributeTypeParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="FloatTypeParam" eSuperTypes="#//AttributeTypeParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringTypeParam" eSuperTypes="#//AttributeTypeParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanTypeParam" eSuperTypes="#//AttributeTypeParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="FileTypeParam" eSuperTypes="#//AttributeTypeParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateTypeParam" eSuperTypes="#//AttributeTypeParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeTypeParam" eSuperTypes="#//AttributeTypeParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateTimeTypeParam" eSuperTypes="#//AttributeTypeParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumTypeParam" eSuperTypes="#//AttributeTypeParam"/>
  <eClassifiers xsi:type="ecore:EClass" name="Workflow" eSuperTypes="#//MD2ModelLayer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="workflowElementEntries"
        upperBound="-1" eType="#//WorkflowElementEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="apps" upperBound="-1" eType="#//App"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowElementEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="workflowElement" eType="#//WorkflowElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invokable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventDesc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="firedEvents" upperBound="-1"
        eType="#//FireEventEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FireEventEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//WorkflowEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startedWorkflowElement"
        eType="#//WorkflowElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endWorkflow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="App">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workflowElements" upperBound="-1"
        eType="#//WorkflowElementReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultConnection" eType="#//RemoteConnection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowElementReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="workflowElementReference"
        eType="#//WorkflowElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Operator">
    <eLiterals name="EQUALS" literal="equals"/>
    <eLiterals name="GREATER" value="1" literal=">"/>
    <eLiterals name="SMALLER" value="2" literal="&lt;"/>
    <eLiterals name="GREATER_OR_EQUAL" value="3" literal=">="/>
    <eLiterals name="SMALLER_OR_EQUAL" value="4" literal="&lt;="/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Boolean">
    <eLiterals name="TRUE" literal="true"/>
    <eLiterals name="FALSE" value="1" literal="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GridLayoutPaneColumnsParam" eSuperTypes="#//GridLayoutPaneParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GridLayoutPaneRowsParam" eSuperTypes="#//GridLayoutPaneParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowLayoutPaneFlowDirectionParam" eSuperTypes="#//FlowLayoutPaneParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flowDirection" eType="#//FlowDirection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidthParam" eSuperTypes="#//CommonContainerParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TabTitleParam" eSuperTypes="#//TabSpecificParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tabTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TabIconParam" eSuperTypes="#//TabSpecificParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tabIcon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerElementReference" eSuperTypes="#//ViewGUIElementReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//TabSpecificParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StyleDefinition" eSuperTypes="#//StyleAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//StyleBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StyleReference" eSuperTypes="#//StyleAssignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Style"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HexColorDef" eSuperTypes="#//Color">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedColorDef" eSuperTypes="#//Color">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//NamedColor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessChainProceedAction" eSuperTypes="#//SimpleAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessChainReverseAction" eSuperTypes="#//SimpleAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessChainGotoAction" eSuperTypes="#//SimpleAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pcStep" eType="#//ProcessChainStep"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetProcessChainAction" eSuperTypes="#//SimpleAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processChain" eType="#//ProcessChain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GotoViewAction" eSuperTypes="#//SimpleAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" eType="#//AbstractViewGUIElementRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisableAction" eSuperTypes="#//SimpleAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputField" eType="#//AbstractViewGUIElementRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnableAction" eSuperTypes="#//SimpleAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputField" eType="#//AbstractViewGUIElementRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisplayMessageAction" eSuperTypes="#//SimpleAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="#//SimpleExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentProviderOperationAction" eSuperTypes="#//SimpleAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="#//AllowedOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProvider" eType="#//AbstractProviderReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentProviderResetAction" eSuperTypes="#//SimpleAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProvider" eType="#//ContentProviderReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FireEventAction" eSuperTypes="#//SimpleAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="workflowEvent" eType="#//WorkflowEvent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebServiceCallAction" eSuperTypes="#//SimpleAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="webServiceCall" eType="#//WebServiceCall"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocationAction" eSuperTypes="#//SimpleAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cityInput" eType="#//AbstractContentProviderPath"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="streetInput" eType="#//AbstractContentProviderPath"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="streetNumberInput" eType="#//AbstractContentProviderPath"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postalInput" eType="#//AbstractContentProviderPath"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="countryInput" eType="#//AbstractContentProviderPath"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="latitude" eType="#//AbstractContentProviderPath"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="longitude" eType="#//AbstractContentProviderPath"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentProviderAddAction" eSuperTypes="#//SimpleAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProvider" eType="#//ContentProviderReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentProviderRemoveAction" eSuperTypes="#//SimpleAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProvider" eType="#//ContentProviderReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whereClause" eType="#//WhereClauseCondition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentProviderGetAction" eSuperTypes="#//SimpleAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProvider" eType="#//AbstractProviderReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whereClause" eType="#//WhereClauseCondition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventBindingTask" eSuperTypes="#//CustomCodeFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//ActionDef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//EventDef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorBindingTask" eSuperTypes="#//CustomCodeFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="validators" upperBound="-1"
        eType="#//ValidatorType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedFields" upperBound="-1"
        eType="#//AbstractViewGUIElementRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventUnbindTask" eSuperTypes="#//CustomCodeFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//ActionDef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//EventDef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorUnbindTask" eSuperTypes="#//CustomCodeFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="validators" upperBound="-1"
        eType="#//ValidatorType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allTypes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedFields" upperBound="-1"
        eType="#//AbstractViewGUIElementRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallTask" eSuperTypes="#//CustomCodeFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//ActionDef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingTask" eSuperTypes="#//CustomCodeFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedViewField" eType="#//AbstractViewGUIElementRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathDefinition" eType="#//AbstractContentProviderPath"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnmappingTask" eSuperTypes="#//CustomCodeFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedViewField" eType="#//AbstractViewGUIElementRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathDefinition" eType="#//AbstractContentProviderPath"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeSetTask" eSuperTypes="#//CustomCodeFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathDefinition" eType="#//ContentProviderPath"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//SimpleExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentProviderSetTask" eSuperTypes="#//CustomCodeFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProvider" eType="#//ContentProviderReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//SimpleExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewElementSetTask" eSuperTypes="#//CustomCodeFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedViewField" eType="#//AbstractViewGUIElementRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//SimpleExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalCodeFragment" eSuperTypes="#//CustomCodeFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="if" eType="#//IfCodeBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseifs" upperBound="-1"
        eType="#//IfCodeBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//ElseCodeBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionReference" eSuperTypes="#//ActionDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionRef" eType="#//Action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleActionRef" eSuperTypes="#//ActionDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//SimpleAction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentProviderPathEventRef" eSuperTypes="#//EventDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathDefinition" eType="#//AbstractContentProviderPath"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="event" eType="#//ContentProviderEventType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentProviderEventRef" eSuperTypes="#//EventDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProvider" eType="#//AbstractProviderReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="event" eType="#//ContentProviderEventType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewElementEventRef" eSuperTypes="#//EventDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedField" eType="#//AbstractViewGUIElementRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="event" eType="#//ElementEventType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalEventRef" eSuperTypes="#//EventDef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="event" eType="#//GlobalEventType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalEventRef" eSuperTypes="#//EventDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventReference" eType="#//OnConditionEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomizedValidatorType" eSuperTypes="#//ValidatorType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="validator" eType="#//Validator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StandardValidatorType" eSuperTypes="#//ValidatorType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="validator" eType="#//StandardValidator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegExValidator" eSuperTypes="#//Validator"/>
  <eClassifiers xsi:type="ecore:EClass" name="NotNullValidator" eSuperTypes="#//Validator"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumberRangeValidator" eSuperTypes="#//Validator"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringRangeValidator" eSuperTypes="#//Validator"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateRangeValidator" eSuperTypes="#//Validator"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeRangeValidator" eSuperTypes="#//Validator"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateTimeRangeValidator" eSuperTypes="#//Validator"/>
  <eClassifiers xsi:type="ecore:EClass" name="StandardNotNullValidator" eSuperTypes="#//StandardValidator"/>
  <eClassifiers xsi:type="ecore:EClass" name="StandardRegExValidator" eSuperTypes="#//StandardValidator"/>
  <eClassifiers xsi:type="ecore:EClass" name="StandardNumberRangeValidator" eSuperTypes="#//StandardValidator"/>
  <eClassifiers xsi:type="ecore:EClass" name="StandardStringRangeValidator" eSuperTypes="#//StandardValidator"/>
  <eClassifiers xsi:type="ecore:EClass" name="StandardDateRangeValidator" eSuperTypes="#//StandardValidator"/>
  <eClassifiers xsi:type="ecore:EClass" name="StandardTimeRangeValidator" eSuperTypes="#//StandardValidator"/>
  <eClassifiers xsi:type="ecore:EClass" name="StandardDateTimeRangeValidator" eSuperTypes="#//StandardValidator"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorRegExParam" eSuperTypes="#//RegExValidatorParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="regEx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorMaxParam" eSuperTypes="#//NumberRangeValidatorParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorMinParam" eSuperTypes="#//NumberRangeValidatorParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorMaxLengthParam" eSuperTypes="#//StringRangeValidatorParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorMinLengthParam" eSuperTypes="#//StringRangeValidatorParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorMaxDateParam" eSuperTypes="#//DateRangeValidatorParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorMinDateParam" eSuperTypes="#//DateRangeValidatorParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorMaxTimeParam" eSuperTypes="#//TimeRangeValidatorParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorMinTimeParam" eSuperTypes="#//TimeRangeValidatorParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorMaxDateTimeParam" eSuperTypes="#//DateTimeRangeValidatorParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidatorMinDateTimeParam" eSuperTypes="#//DateTimeRangeValidatorParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferencedModelType" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleType" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SimpleDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhereClauseOr" eSuperTypes="#//WhereClauseConditionalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftExpression" eType="#//WhereClauseConditionalExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightExpression" eType="#//WhereClauseConditionalExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhereClauseAnd" eSuperTypes="#//WhereClauseConditionalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftExpression" eType="#//WhereClauseConditionalExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightExpression" eType="#//WhereClauseConditionalExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhereClauseNot" eSuperTypes="#//WhereClauseConditionalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//WhereClauseConditionalExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhereClauseCompareExpression" eSuperTypes="#//WhereClauseConditionalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eqLeft" eType="#//EntityPath"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//Operator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eqRight" eType="#//SimpleExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessChainGoToNext" eSuperTypes="#//ProcessChainGoTo"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessChainGoToPrevious" eSuperTypes="#//ProcessChainGoTo"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessChainReturn" eSuperTypes="#//ProcessChainGoTo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStep" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeDirection" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessChainGoToStep" eSuperTypes="#//ProcessChainGoTo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processChainStep" eType="#//ProcessChainStep"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnTo" eType="#//ProcessChainStep"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessChainGoToSpecShorthand" eSuperTypes="#//ProcessChainGoToSpec"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessChainGoToSpecExtended" eSuperTypes="#//ProcessChainGoToSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//ConditionalExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//ActionDef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeWSParam" eSuperTypes="#//InvokeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeDefaultValue" eSuperTypes="#//InvokeParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invokeValue" eType="#//InvokeValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeSetContentProvider" eSuperTypes="#//InvokeParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProvider" eType="#//ContentProviderReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeStringValue" eSuperTypes="#//InvokeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeIntValue" eSuperTypes="#//InvokeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeBooleanValue" eSuperTypes="#//InvokeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeDateValue" eSuperTypes="#//InvokeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeTimeValue" eSuperTypes="#//InvokeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeDateTimeValue" eSuperTypes="#//InvokeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeFloatValue" eSuperTypes="#//InvokeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//ConditionalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftExpression" eType="#//ConditionalExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightExpression" eType="#//ConditionalExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//ConditionalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftExpression" eType="#//ConditionalExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightExpression" eType="#//ConditionalExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="#//ConditionalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//ConditionalExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression" eSuperTypes="#//ConditionalExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuiElementStateExpression" eSuperTypes="#//ConditionalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//AbstractViewGUIElementRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isState" eType="#//ViewElementState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompareExpression" eSuperTypes="#//ConditionalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eqLeft" eType="#//SimpleExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="op" eType="#//Operator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eqRight" eType="#//SimpleExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringRestParam" eSuperTypes="#//RESTValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerRestParam" eSuperTypes="#//RESTValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanRestParam" eSuperTypes="#//RESTValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatRestParam" eSuperTypes="#//RESTValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentProviderRestParam" eSuperTypes="#//RESTValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ContentProviderPath"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcatenatedString" eSuperTypes="#//SimpleExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftString" eType="#//SimpleExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightString" eType="#//SimpleExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringVal" eSuperTypes="#//SimpleExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanVal" eSuperTypes="#//SimpleExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateVal" eSuperTypes="#//SimpleExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeVal" eSuperTypes="#//SimpleExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateTimeVal" eSuperTypes="#//SimpleExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntVal" eSuperTypes="#//SimpleExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatVal" eSuperTypes="#//SimpleExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plus" eSuperTypes="#//SimpleExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" eType="#//SimpleExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" eType="#//SimpleExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Minus" eSuperTypes="#//SimpleExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" eType="#//SimpleExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" eType="#//SimpleExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mult" eSuperTypes="#//SimpleExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" eType="#//SimpleExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" eType="#//SimpleExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Div" eSuperTypes="#//SimpleExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" eType="#//SimpleExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" eType="#//SimpleExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferencedType" eSuperTypes="#//AttributeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//ReferencedTypeParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerType" eSuperTypes="#//AttributeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//IntegerTypeParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatType" eSuperTypes="#//AttributeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//FloatTypeParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//AttributeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//StringTypeParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//AttributeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//BooleanTypeParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateType" eSuperTypes="#//AttributeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//DateTypeParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeType" eSuperTypes="#//AttributeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//TimeTypeParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateTimeType" eSuperTypes="#//AttributeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//DateTimeTypeParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileType" eSuperTypes="#//AttributeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//FileTypeParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumType" eSuperTypes="#//AttributeType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumBody" eType="#//EnumBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//EnumTypeParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrIsOptional" eSuperTypes="#//ReferencedTypeParam #//IntegerTypeParam #//FloatTypeParam #//StringTypeParam #//BooleanTypeParam #//FileTypeParam #//DateTypeParam #//TimeTypeParam #//DateTimeTypeParam #//EnumTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrEnumDefault" eSuperTypes="#//ReferencedTypeParam #//EnumTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrIdentifier" eSuperTypes="#//IntegerTypeParam #//StringTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrIntDefault" eSuperTypes="#//IntegerTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrIntMax" eSuperTypes="#//IntegerTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrIntMin" eSuperTypes="#//IntegerTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrFloatDefault" eSuperTypes="#//FloatTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrFloatMax" eSuperTypes="#//FloatTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrFloatMin" eSuperTypes="#//FloatTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrStringDefault" eSuperTypes="#//StringTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrStringMax" eSuperTypes="#//StringTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrStringMin" eSuperTypes="#//StringTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrBooleanDefault" eSuperTypes="#//BooleanTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrDateDefault" eSuperTypes="#//DateTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrDateMax" eSuperTypes="#//DateTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrDateMin" eSuperTypes="#//DateTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrTimeDefault" eSuperTypes="#//TimeTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrTimeMax" eSuperTypes="#//TimeTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrTimeMin" eSuperTypes="#//TimeTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrDateTimeDefault" eSuperTypes="#//DateTimeTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrDateTimeMax" eSuperTypes="#//DateTimeTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttrDateTimeMin" eSuperTypes="#//DateTimeTypeParam">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
</ecore:EPackage>
