/*
 * generated by Xtext 2.13.0
 */
package de.wwu.md2.framework


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MD2RuntimeModule extends AbstractMD2RuntimeModule {
}
