/*
 * generated by Xtext
 */
package de.wwu.md2.framework;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MD2RuntimeModule extends de.wwu.md2.framework.AbstractMD2RuntimeModule {

}
