/*
 * generated by Xtext
 */
package de.wwu.md2.framework.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.ComposedChecks;

@ComposedChecks(validators= {org.eclipse.xtext.validation.ImportUriValidator.class, de.wwu.md2.framework.validation.MD2NamesAreUniqueValidator.class})
public class AbstractMD2JavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.wwu.md2.framework.mD2.MD2Package.eINSTANCE);
		return result;
	}

}
