/*
 * generated by Xtext
 */
package de.wwu.md2.framework.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.wwu.md2.framework.ui.internal.MD2Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MD2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MD2Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MD2Activator.getInstance().getInjector(MD2Activator.DE_WWU_MD2_FRAMEWORK_MD2);
	}
	
}
