/*
 * generated by Xtext 2.13.0
 */
package de.wwu.md2.framework.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MD2UiModule extends AbstractMD2UiModule {
}
