/*
 * generated by Xtext
 */
package de.wwu.md2.framework.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MD2AntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/wwu/md2/framework/parser/antlr/internal/InternalMD2.tokens");
	}
}
