/*
 * generated by Xtext
 */
package de.wwu.md2.framework.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.wwu.md2.framework.services.MD2GrammarAccess;

public class MD2Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MD2GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.wwu.md2.framework.parser.antlr.internal.InternalMD2Parser createParser(XtextTokenStream stream) {
		return new de.wwu.md2.framework.parser.antlr.internal.InternalMD2Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "MD2Model";
	}
	
	public MD2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MD2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
