/*
 * generated by Xtext 2.13.0
 */
package de.wwu.md2.framework.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class MD2WizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public MD2WizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
