package de.wwu.md2.framework.generator.android.common;

@SuppressWarnings("all")
public class ProjectProperties {
  public static CharSequence projectProperties(final int minAppVersion) {
    org.eclipse.xtend2.lib.StringConcatenation _builder = new org.eclipse.xtend2.lib.StringConcatenation();
    _builder.append("# This file is automatically generated by Android Tools.");
    _builder.newLine();
    _builder.append("# Do not modify this file -- YOUR CHANGES WILL BE ERASED!");
    _builder.newLine();
    _builder.append("#");
    _builder.newLine();
    _builder.append("# This file must be checked in Version Control Systems.");
    _builder.newLine();
    _builder.append("#");
    _builder.newLine();
    _builder.append("# To customize properties used by the Ant build system edit");
    _builder.newLine();
    _builder.append("# \"ant.properties\", and override values to adapt the script to your");
    _builder.newLine();
    _builder.append("# project structure.");
    _builder.newLine();
    _builder.append("#");
    _builder.newLine();
    _builder.append("# To enable ProGuard to shrink and obfuscate your code, uncomment this (available properties: sdk.dir, user.home):");
    _builder.newLine();
    _builder.append("#proguard.config=${sdk.dir}\\tools\\proguard\\proguard-android.txt:proguard-project.txt");
    _builder.newLine();
    _builder.newLine();
    _builder.append("# Project target.");
    _builder.newLine();
    _builder.append("target=android-");
    _builder.append(minAppVersion, "");
    _builder.newLineIfNotEmpty();
    return _builder;
  }
}
